// <auto-generated />
namespace Eventplanner.DataAccess
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class EmployeePerson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmployeePerson));
        
        string IMigrationMetadata.Id
        {
            get { return "202407240712405_EmployeePerson"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
