// <auto-generated />
namespace Eventplanner.DataAccess
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Appointments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Appointments));
        
        string IMigrationMetadata.Id
        {
            get { return "202407250636223_Appointments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
